name: Build on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MSVC v142
      uses: mithun-daa/setup-msvc@v1

    - name: Install CMake
      uses: chrispat/setup-cmake@v2
      with:
        cmake-version: '3.21.4'

    - name: Install Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set up longer paths (if needed)
      run: |
        REG ADD HKLM\SYSTEM\CurrentControlSet\Control\FileSystem /v LongPathsEnabled /t REG_DWORD /d 1 /f
      if: runner.os == 'Windows'

    - name: Configure and build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
        cmake --build . --config Release
      working-directory: ${{ github.workspace }}

    - name: Test (if applicable)
      run: |
        # Add commands to run tests if applicable
      working-directory: ${{ github.workspace }}
