name: Build osquery for macOS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install prerequisites
      run: |
        brew install ccache git git-lfs cmake python clang-format flex bison

    - name: Install Python test prerequisites
      run: |
        pip3 install --user setuptools pexpect==3.3 psutil timeout_decorator six thrift==0.11.0 osquery

    - name: Download and build osquery
      run: |
        git clone https://github.com/osquery/osquery
        cd osquery
        mkdir build
        cd build
        cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
        cmake --build . -j $(sysctl -n hw.ncpu)
        mkdir package_data
        export DESTDIR=$(pwd)/package_data
        cmake --build . --target install
    
    - name: Create PKG
      run: |
        # Create the PKG creation script
        cat << 'EOF' > create_pkg.sh
#!/bin/bash

# Define the paths to your built osquery components
# Define the paths to your built osquery components
osqueryd: "/osquery/build/osquery/build/package_data/Program Files/osquery/osqueryd/osqueryd.exe"
osqueryConf: "/osquery/build/osquery/build/package_data/Program Files/osquery/osqueryd/osquery.conf"
osqueryiBinaryPath: "osquery/build/osquery/build/package_data/Program Files/osquery/osqueryd/osqueryi.exe"


# Create a directory for the package contents
pkg_dir: "/osquery/build/osquery/build/package_data"
mkdir -p "$pkg_dir"

# Copy the osquery components to the package directory
cp "$osqueryd" "$pkg_dir"
cp "$osqueryConf" "$pkg_dir"
cp "$osqueryiBinaryPath" "$pkg_dir"

# Create the PKG using pkgbuild
pkgbuild --root "$pkg_dir" --install-location / --version 1.0 --identifier com.example.osquery osquery.pkg

# Create a product distribution using productbuild
productbuild --distribution distribution.xml --package-path . osquery_installer.pkg

# Clean up the temporary package_data directory
rm -r "$pkg_dir"
EOF

        # Make the script executable
        chmod +x create_pkg.sh

        # Execute the PKG creation script
        ./create_pkg.sh

    - name: Upload PKG artifact
      uses: actions/upload-artifact@v2
      with:
        name: osquery_installer.pkg
        path: osquery_installer.pkg
